spring:
  application:
    name: UserService
  liquibase:
    enabled: true
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cache:
    type: redis
    redis:
      time-to-live: 5m
      cache-null-values: false
server:
  port: 8080
